services:
  - type: web
    name: msm_we_2024_9_1_sdf
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: msm_we_2024_9_1_sdf
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

databases:
  - name: msm_we_2024_9_1_sdf
    databaseName: msm_we_2024_9_1_sdf
    user: msm_we_2024_9_1_sdf
    plan: free
